[package]
name = "libmedusa-zip"
version = "0.0.0"
authors = ["Danny McClanahan <dmcC2@hypnicjerk.ai>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
