name: CI

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request: {}

jobs:
  test-py:
    runs-on: ubuntu-latest
    name: test ${{ matrix.python-version }} rust ${{ matrix.rust-toolchain }}
    strategy:
      fail-fast: false
      matrix:

        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
        rust-toolchain: ['stable', 'nightly']

    env:
      PYTHON: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v3

    - name: set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - run: pip install --upgrade pip

    - name: install rust ${{ matrix.rust-toolchain }}
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust-toolchain }}

    - id: cache-rust
      name: cache rust
      uses: Swatinem/rust-cache@v2
      with:
        key: v1

    - run: pip install -e .

  test-rust:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - run: pip install --upgrade pip

    - name: install rust nightly
      uses: dtolnay/rust-toolchain@nightly

    - id: cache-rust
      name: cache rust
      uses: Swatinem/rust-cache@v2
      with:
        key: v1

    - name: test rust
      run: cargo test

  lint-rust:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - run: pip install --upgrade pip

    - name: install rust nightly
      uses: dtolnay/rust-toolchain@nightly
      with:
        components: rustfmt, clippy

    - id: cache-rust
      name: cache rust
      uses: Swatinem/rust-cache@v2
      with:
        key: v1

    - name: fmt rust
      run: cargo fmt --check

    - name: clippy rust
      run: cargo clippy

  lint-py:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - run: pip install --upgrade pip

    - uses: isort/isort-action@master
      with:
        sortPaths: "py"

  # https://github.com/marketplace/actions/alls-green#why used for branch protection checks
  check:
    if: always()
    needs: [test-py, test-rust, lint-rust, lint-py]
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}

  build:
    name: build on ${{ matrix.os }} (${{ matrix.target }} - ${{ matrix.manylinux || 'auto' }})
    # run on push to main, on release, and on PRs with the label 'Full Build'
    if: "success() && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'Full Build'))"
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu, macos, windows]
        os: [ubuntu]

    runs-on: ${{ matrix.os }}-latest

    steps:
    - uses: actions/checkout@v3

    - name: set up python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.python-architecture || 'x64' }}

    - run: pip install --upgrade pip

    # - name: install rust stable
    #   uses: dtolnay/rust-toolchain@stable

    # - id: cache-rust
    #   name: cache rust
    #   uses: Swatinem/rust-cache@v2
    #   with:
    #     key: v1

    - name: build sdist
      if: ${{ matrix.os == 'ubuntu' && matrix.target == 'x86_64' && matrix.manylinux == 'auto' }}
      run: python setup.py sdist

    - name: build wheels
      uses: pypa/cibuildwheel@v2.14.1

    - name: check outputs
      run: ls -lAvFh dist/

    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: pypi_files
    #     path: dist

  # inspect-pypi-assets:
  #   needs: [build]
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: get dist artifacts
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: pypi_files
  #         path: dist

  #     - name: list dist files
  #       run: |
  #        ls -lh dist/
  #        echo "`ls dist | wc -l` files"

  #     - name: extract and list sdist file
  #       run: |
  #        mkdir sdist-files
  #        tar -xvf dist/*.tar.gz -C sdist-files
  #        tree -a sdist-files

  #     - name: extract and list wheel file
  #       run: |
  #        ls dist/*cp310-manylinux*x86_64.whl | head -n 1
  #        python -m zipfile --list `ls dist/*cp310-manylinux*x86_64.whl | head -n 1`

  #     - run: pip install twine
  #     - run: twine check dist/*
